### ISSUE TITLE
玩家举报∶ [请填写被举报玩家ID]wawawa

### ISSUE THREAD

**Issue by Templeovo** [ScaxeTeam/server-report#1]
# 举报务必配有视频/图片证据及相关描述
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请在以下填写玩家被举报原因
zc火弓射我被我看到还骂我狡辩并搞领地骂我

- 请在以下粘贴图片/视频证据
- 手机打不开上传图片
- 已私聊发了

- 请在以下留下本人可用联系方式(QQ号/邮箱等)
1446247945@qq.com

下滑，点击 "Submit new issue"提交举报

**Comment by Sunch233** [comment]
领地已经删除，账号wawawa已经封号，剩下的牌子啥的自己处理
