### ISSUE TITLE
玩家举报∶ jkd3699wcnm

### ISSUE THREAD

**Issue by rpg636zjhi** [ScaxeTeam/server-report#11]
# 请在标题填写举报玩家ID
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请在以下填写玩家被举报原因

开户籍

- 请在以下粘贴图片/视频证据

![Screenshot_20241205_125007](https://github.com/user-attachments/assets/28b9569a-af28-4cb2-9c8f-e557b41b913b)

- 请在以下留下本人可用联系方式(QQ号/邮箱等)和本人服务器ID

3187735201@qq.com
3187735201

下滑，点击 "Submit new issue"提交举报

**Comment by rpg636zjhi** [comment]
![Screenshot_20241205_124922](https://github.com/user-attachments/assets/b33b98f1-65db-4585-98c5-55cf7b625447)
![Screenshot_20241205_124819](https://github.com/user-attachments/assets/8939e6e0-7ee8-4393-8b3c-fbbc7ad6a7e7)

**Comment by Sunch233** [comment]
已封号
