### ISSUE TITLE
狙击手小窝

### ISSUE THREAD

**Issue by zxy512zxy** [ScaxeTeam/server-report#13]
## 务必尽可能详细的填写信息

-----

# 正文
- 请填写组织用途
继《我的世界之梦想之城》这部小说里的狙击手小窝进行传承，虽不能继续空间样貌但会继承其建筑特色

- 请填写组织主要管理者服务器ID，QQ号(必填)
- zxy512zxy
- 2277549843

- 组织创建人服务器注册时长(/qd)截图
![Uploading Screenshot_20241207_203817_com.mojang.minecraftpe.liuliang.jpg…]()

- 如果建立QQ群，请在此特殊说明
建立qq群

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
需要账号/qd具体图片

**Comment by zxy512zxy** [comment]
o



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月06日 20:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ScaxeTeam/server-report] 狙击手小窝 (Issue #13) |

需要账号/qd具体图片

**Comment by Sunch233** [comment]
图片与陈述事实不符，注册天数一样且遮挡玩家ID
