### ISSUE TITLE
服务器组织申请: [铃兰共和]

### ISSUE THREAD

**Issue by yechen163** [ScaxeTeam/server-report#14]
## 务必尽可能详细的填写信息

-----

# 正文
- 请填写组织用途
- 建造建筑
- 药水制作
- pvp
- 商品开发
- 商业交流

- 请填写组织主要管理者服务器ID，QQ号(161195374)
yechen163

- 组织创建人服务器注册时长(/qd)截图
307

- 如果建立QQ群，请在此特殊说明
建立

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
需要qd截图，不是文字

**Comment by Sunch233** [comment]
直接在issue下面留言或者edit就行，不要再开新issue了，最后一次说了

**Comment by yechen163** [comment]
![Screenshot_2024-12-15-20-01-27-66_29414d53f4a03bf7281d738867321567](https://github.com/user-attachments/assets/77584b02-f20b-4716-a6e0-5ad6e152d88c)
![Screenshot_2024-12-15-20-01-27-66_29414d53f4a03bf7281d738867321567](https://github.com/user-attachments/assets/325bdf94-5309-4056-ab12-57de11379e5e)

**Comment by yechen163** [comment]
![Screenshot_2024-12-15-20-01-27-66_29414d53f4a03bf7281d738867321567](https://github.com/user-attachments/assets/9006c1b8-07f0-447c-a021-76a57d248b9a)
图片

**Comment by Sunch233** [comment]
批准
