### ISSUE TITLE
Xiaoao5297 : 忘记密码

### ISSUE THREAD

**Issue by Xiaoao5297** [ScaxeTeam/server-report#15]
# 请根据自身情况填写标题
## 务必尽可能详细的填写信息

-----

# 正文
qq：2574459918

- 内容
忘记密码了，本来zxcvbnmqa叫我玩scf，但是忘记密码登不了，里面有重要的数据，希望把密码改了。

**Comment by Sunch233** [comment]
QQ回信，确认是本人后就可以找回
