### ISSUE TITLE
[pvptemple]∶ [希望支付1.5万块钱的材料费来重建那个标余下的钱用来装饰场地如果还有剩余的我会转回]

### ISSUE THREAD

**Issue by Templeovo** [ScaxeTeam/server-report#16]
# 请根据自身情况填写标题
## 务必尽可能详细的填写信息

-----

# 正文
- 本人联系方式(必填)
1446247945@qq.com

- 内容
- 申请材料费

下滑，点击 "Submit new issue"提交

**Comment by Sunch233** [comment]
批准，钱已到账
原因: 三周年广场遭受巨大熊服
