### ISSUE TITLE
狙击手小窝

### ISSUE THREAD

**Issue by zxy512zxy** [ScaxeTeam/server-report#17]
## 务必尽可能详细的填写信息

-----

# 正文
- 请填写组织用途
给玩家安身之所，互帮互助
继承狙击手小窝特色

- 请填写组织主要管理者服务器ID，QQ号(必填)
zxy512zxy
2277549843

- 组织创建人服务器注册时长(/qd)截图
![Screenshot_20241207_203817_com mojang minecraftpe liuliang](https://github.com/user-attachments/assets/67f57502-91e3-4b37-a5eb-a9b577f7bb94)

- 如果建立QQ群，请在此特殊说明
建立

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
批准
