### ISSUE TITLE
银灰之意第一帝国

### ISSUE THREAD

**Issue by mcxg** [ScaxeTeam/server-report#2]
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请填写组织用途
私人性质
组织用于局部群体玩家的建设，例如共同建筑、年度事件等，可能有其他组织发生冲突、交易关系。
组织还将尝试发展银行储蓄体系。
- 请填写组织主要管理者服务器ID，QQ号(必填)
"银灰之意第一帝国" 主要代表 :
ID: Nalanko
QQ:2169939383
- 如果建立QQ群，请在此特殊说明
无

备注:
本代表人承诺已经了解相关违规行为，不会以组织形式破坏其他玩家游戏体验，不恶意卡服、刷屏，有问题积极整改，维护SCAXE环境

**Comment by Sunch233** [comment]
批准，组织列表稍后添加
