### ISSUE TITLE
[Safari_Browse]∶ [三周年广场附近的低俗建筑]

### ISSUE THREAD

**Issue by Rongxuan2333** [ScaxeTeam/server-report#24]
# 请根据自身情况填写标题
## 务必尽可能详细的填写信息

-----

# 正文
- 本人联系方式(必填)
邮箱：Rongxuan2022@qq.com

- 内容
![Screenshot_20241214_204203_com mojang minecraftpe5464](https://github.com/user-attachments/assets/dc05787d-3ad7-417f-bbdd-883f52a592d0)

如上图
希望可以查下是谁干的

下滑，点击 "Submit new issue"提交

**Comment by Sunch233** [comment]
你自己不可以/zp i 一下吗
