### ISSUE TITLE
服务器组织申请: [极乐联邦]

### ISSUE THREAD

**Issue by conglobate** [ScaxeTeam/server-report#27]
## 务必尽可能详细的填写信息

-----

# 正文
- 请填写组织用途

搭建建筑，帮助建筑

帮助新人，互帮互助

酿造药水，售卖药水

PVP

- 请填写组织主要管理者服务器ID，QQ号(必填)
conglobate
（3937072036）

- 组织创建人服务器注册时长(/qd)截图
6天
![Screenshot_2024-12-16-22-08-21-889_com mojang minecraftpe](https://github.com/user-attachments/assets/1204b9ae-d259-4327-8b91-1abfafb94434)

- 如果建立QQ群，请在此特殊说明
 无

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
需要进服超过90天才可申请组织
