### ISSUE TITLE
玩家举报∶ [XTYqq]

### ISSUE THREAD

**Issue by mcxg** [ScaxeTeam/server-report#28]
# 请在标题填写举报玩家ID
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请在以下填写玩家被举报原因
恶意破坏店铺

- 请在以下粘贴图片/视频证据

- 请在以下留下本人可用联系方式(QQ号/邮箱等)和本人服务器ID
HUYouran123
2728426823

下滑，点击 "Submit new issue"提交举报

**Comment by mcxg** [comment]
![Uploading a.jpg…]()

**Comment by Sunch233** [comment]
图片未正确上传
