### ISSUE TITLE
玩家举报∶ [cxj2013 qwe101010 662345]

### ISSUE THREAD

**Issue by Templeovo** [ScaxeTeam/server-report#3]
# 举报务必配有视频/图片证据及相关描述
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请在以下填写玩家被举报原因
czj2013故意骂人(在群)
qwe101010之前开挂解ban后骂人
662345开fly speed hobo

- 请在以下粘贴图片/视频证据
- 相关文件打不开上传不了
- 已私发

- 请在以下留下本人可用联系方式(QQ号/邮箱等)
1446247945@qq.com

下滑，点击 "Submit new issue"提交举报

**Comment by Sunch233** [comment]
qwe101010处理过了
czj2013证据没发

**Comment by Sunch233** [comment]
cxj2013属于组织内部问题，其他的人封号了
