### ISSUE TITLE
玩家举报∶ January

### ISSUE THREAD

**Issue by pgcccc** [ScaxeTeam/server-report#4]
事件经过：
1. 22年前后，我获得了原ptp大厦26F的居住权，始终是其业主；

2. 22年之后我一直没有玩服务器，直到一个月前左右我再次进服，发现我的住所被BBC组织抢占，经过群内询问，管理员告知BBC已经被ban，无需担心，将bbc所建拆除即可；（图片详见IMG_0949~0952）
![IMG_0949](https://github.com/user-attachments/assets/a8a90f38-fc80-4932-818f-7fbec5e8c10f)
![IMG_0950](https://github.com/user-attachments/assets/51a0f5da-be68-4b6b-ae24-8a7e47e1ecea)
![IMG_0951](https://github.com/user-attachments/assets/eef744cc-630a-463d-a841-469f33545bfa)
![IMG_0952](https://github.com/user-attachments/assets/da91c9d4-c0ad-4df2-a17c-60a0ca6f1291)

3. 然而January（所谓的BBC）实际上并没有被ban，随后他发现我的改动，并直接要求管理员"PTP"将我的楼层买下来，交易已经完成，但是**整个过程我完全不知情，整个交易流程都没有经过我的允许，January只是出于原业主已退坑的揣测就将其归为己有，更何况退坑玩家的领土也不应被随便转让**（详见IMG_0953~0957）
![IMG_0953](https://github.com/user-attachments/assets/b9df6294-be93-441c-a5fa-7717307f3f5c)
![IMG_0954](https://github.com/user-attachments/assets/baa5c321-58c9-4553-8a60-97b76e970067)
![IMG_0955](https://github.com/user-attachments/assets/7cb01532-7ce0-4753-89fc-fd99667db850)
![IMG_0956](https://github.com/user-attachments/assets/7362d879-8bdc-413b-94c5-668f91243301)
![IMG_0957](https://github.com/user-attachments/assets/791d06d5-5aa2-4cbb-9aeb-a92092c9f0c6)

4. 11月30日也就是今天，我再次查看服务器，发现我的家再次被篡改，为January所做；随后与其协商无果。
![IMG_0940](https://github.com/user-attachments/assets/5d95cb1d-9da5-48f0-9ab6-9d6e72e6808e)
![IMG_0941](https://github.com/user-attachments/assets/1594ae0c-cca6-40b4-bf84-2b6c30988474)
----------------------------------
诉求：
**希望能够拿回自己的楼层，并明确相关规定，禁止此类行为再次发生**
----------------------------------
本人联系方式：
QQ：3279368927

**Comment by Sunch233** [comment]
联系方式没写

**Comment by pgcccc** [comment]
> 联系方式没写

现在写了

**Comment by Sunch233** [comment]
退坑玩家回归，因为闲置太久已处理的领地是否物归原主应该由回归玩家本人定夺

内一层楼你要是索要就是应该给你的，我已经在当地写好告示牌了，如果bbc有问题让他来直接找我

**Comment by pgcccc** [comment]
> 退坑玩家回归，因为闲置太久已处理的领地是否物归原主应该由回归玩家本人定夺
> 
> 内一层楼你要是索要就是应该给你的，我已经在当地写好告示牌了，如果bbc有问题让他来直接找我

好的谢谢
