### ISSUE TITLE
铃兰共和

### ISSUE THREAD

**Issue by yechen163** [ScaxeTeam/server-report#5]
## 务必尽可能详细的填写信息

-----

# 正文
- 请填写组织用途
- 建筑

- 请填写组织主要管理者服务器ID，QQ号(必填)
161195374

- 如果建立QQ群，请在此特殊说明
需要

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
管理这服务器ID没填写，另外请确认组织名字就是这四个字
