### ISSUE TITLE
服务器组织申请: [铃兰共和]

### ISSUE THREAD

**Issue by yechen163** [ScaxeTeam/server-report#6]
## 务必尽可能详细的填写信息

-----确认组织名称  铃兰共和

# 正文
- 请填写组织用途
建筑

- 请填写组织主要管理者服务器ID，QQ号(必填)
yechen163
161195374

- 如果建立QQ群，请在此特殊说明
需要

下滑，点击 "Submit new issue"提交申请

**Comment by Sunch233** [comment]
组织用途过于宽泛

**Comment by Sunch233** [comment]
七天不处理即视为自动放弃
