### ISSUE TITLE
玩家举报∶ sparka14

### ISSUE THREAD

**Issue by rpg636zjhi** [ScaxeTeam/server-report#7]
# 举报务必配有视频/图片证据及相关描述
## 务必尽可能详细的填写信息

-----

# 举报正文
- 请在以下填写玩家被举报原因
骂人

- 请在以下粘贴图片/视频证据
![f7ab64eb71b0cb25c78f7a0cbcc6ddd4](https://github.com/user-attachments/assets/008eaadc-d37e-4060-a643-bb9cc8baef46)

- 请在以下留下本人可用联系方式(QQ号/邮箱等)和本人服务器ID

3187735201
3187735201@qq.com
rpg636zjhi

下滑，点击 "Submit new issue"提交举报

**Comment by Sunch233** [comment]
举报ID在哪?

**Comment by rpg636zjhi** [comment]
sparkal4

**Comment by Sunch233** [comment]
封号
