### ISSUE TITLE
玩家举报∶ wsyhwjdh123

### ISSUE THREAD

**Issue by TX666-STAR** [ScaxeTeam/server-report#8]
# 请在标题填写举报玩家ID
## 务必尽可能详细的填写信息

-----wsyhwjdh123

# 举报正文
- 请在以下填写玩家被举报原因

乱锁我箱子

- 请在以下粘贴图片/视频证据

![Screenshot_20241129_224603](https://github.com/user-attachments/assets/60a47c48-e4f3-4b69-be81-98112ee8fc23)

- 请在以下留下本人可用联系方式(QQ号/邮箱等)和本人服务器ID

3299579357 tx666

下滑，点击 "Submit new issue"提交举报

**Comment by Sunch233** [comment]
箱子里有东西吗

**Comment by Sunch233** [comment]
已强拆
